/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.puntodeventa.mvc.Views;

import com.puntodeventa.global.Entity.Compra;
import com.puntodeventa.global.Entity.Product;
import com.puntodeventa.global.Entity.Proveedor;
import com.puntodeventa.global.Util.ValidacionForms;
import com.puntodeventa.mvc.Controller.ProductLogic;
import com.puntodeventa.mvc.Controller.ProveedorLogic;
import com.puntodeventa.mvc.Model.CompraDetalle;
import com.puntodeventa.services.DAO.CompraDAO;
import com.puntodeventa.services.DAO.ProveedorDAO;
import java.awt.event.KeyEvent;
import java.math.BigInteger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nato
 */
public class jfrmProveedor extends javax.swing.JInternalFrame {    
    CompraDAO compraDAO = new CompraDAO();
    static ProveedorDAO proveedorDAO = new ProveedorDAO();
    DefaultTableModel modelo = new DefaultTableModel();
    static ValidacionForms val = new ValidacionForms();
    private static String mensaje;
    static int vActivo;
    /**
     * Creates new form jfrmCompra
     */
    public jfrmProveedor() {
        initComponents();
        val.centerFrame(this);
        if(true == this.getTitleTable()){}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtbpCompra = new javax.swing.JTabbedPane();
        jpnProveedor = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxtClaveProveedor = new javax.swing.JTextField();
        jbtnBusca = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jtxtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtDireccion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtTelefono = new javax.swing.JTextField();
        jbtnGuarda = new javax.swing.JButton();
        jbtnCancelaBusqueda = new javax.swing.JButton();
        jbtnComprar = new javax.swing.JButton();
        jpnAddProduct = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jtxtId_Product = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtxtProduct = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtxtDescripcion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtxtPrecioCompra = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtxtPrecioVenta = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtxtCantidad = new javax.swing.JTextField();
        jchkActivo = new javax.swing.JCheckBox();
        jbtnCancelar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jbtnRCompra = new javax.swing.JButton();
        jbtnBuscaArt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblProduct = new javax.swing.JTable();
        jbtnAgregar = new javax.swing.JButton();
        jlblCantidad = new javax.swing.JLabel();

        setClosable(true);

        jpnProveedor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Agregue, Modifique y Consulte Proveedores", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Proveedor:");

        jtxtClaveProveedor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jbtnBusca.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnBusca.setText("Buscar");
        jbtnBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBuscaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Nombre:  ");

        jtxtNombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Direccion:  ");

        jtxtDireccion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Telefono:");

        jtxtTelefono.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jbtnGuarda.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnGuarda.setText("Guardar");
        jbtnGuarda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGuardaActionPerformed(evt);
            }
        });

        jbtnCancelaBusqueda.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnCancelaBusqueda.setText("Cancelar Busqueda");
        jbtnCancelaBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelaBusquedaActionPerformed(evt);
            }
        });

        jbtnComprar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnComprar.setText("Comprar a");
        jbtnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnComprarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnProveedorLayout = new javax.swing.GroupLayout(jpnProveedor);
        jpnProveedor.setLayout(jpnProveedorLayout);
        jpnProveedorLayout.setHorizontalGroup(
            jpnProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnProveedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnProveedorLayout.createSequentialGroup()
                        .addGap(0, 358, Short.MAX_VALUE)
                        .addComponent(jbtnCancelaBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnGuarda, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpnProveedorLayout.createSequentialGroup()
                        .addGroup(jpnProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpnProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtNombre)
                            .addComponent(jtxtDireccion)
                            .addComponent(jtxtTelefono)
                            .addGroup(jpnProveedorLayout.createSequentialGroup()
                                .addComponent(jtxtClaveProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jpnProveedorLayout.setVerticalGroup(
            jpnProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnProveedorLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jpnProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtClaveProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnBusca))
                .addGap(18, 18, 18)
                .addGroup(jpnProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpnProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnGuarda)
                    .addComponent(jbtnCancelaBusqueda)
                    .addComponent(jbtnComprar))
                .addContainerGap(242, Short.MAX_VALUE))
        );

        jtbpCompra.addTab("Proveedor", jpnProveedor);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Codigo:");

        jtxtId_Product.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jtxtId_Product.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtId_ProductKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtId_ProductKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Producto:");

        jtxtProduct.setEditable(false);
        jtxtProduct.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jtxtProduct.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtProductKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Descripcion:");

        jtxtDescripcion.setEditable(false);
        jtxtDescripcion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jtxtDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDescripcionActionPerformed(evt);
            }
        });
        jtxtDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtDescripcionKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Precio Compra:");

        jtxtPrecioCompra.setEditable(false);
        jtxtPrecioCompra.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jtxtPrecioCompra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtPrecioCompraKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Precio Venta:");

        jtxtPrecioVenta.setEditable(false);
        jtxtPrecioVenta.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jtxtPrecioVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtPrecioVentaKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Cantidad:");

        jtxtCantidad.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jtxtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtCantidadKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtCantidadKeyTyped(evt);
            }
        });

        jchkActivo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jchkActivo.setText("Activo");

        jbtnCancelar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtnCancelar.setText("Cancelar");
        jbtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelarActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Agregue, Modifique Articulos de su Inventario");
        jLabel13.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jbtnRCompra.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtnRCompra.setText("Realizar Compra");
        jbtnRCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRCompraActionPerformed(evt);
            }
        });

        jbtnBuscaArt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnBuscaArt.setText("Buscar");
        jbtnBuscaArt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBuscaArtActionPerformed(evt);
            }
        });

        jtblProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Producto / Descripcion", "P / Compra", "P / Venta", "Cantidad"
            }
        ));
        jScrollPane1.setViewportView(jtblProduct);

        jbtnAgregar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtnAgregar.setText("Agregar");
        jbtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAgregarActionPerformed(evt);
            }
        });

        jlblCantidad.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlblCantidad.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblCantidad.setText("0");
        jlblCantidad.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jpnAddProductLayout = new javax.swing.GroupLayout(jpnAddProduct);
        jpnAddProduct.setLayout(jpnAddProductLayout);
        jpnAddProductLayout.setHorizontalGroup(
            jpnAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(jpnAddProductLayout.createSequentialGroup()
                .addGroup(jpnAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnAddProductLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jpnAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnAddProductLayout.createSequentialGroup()
                                .addGroup(jpnAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(11, 11, 11)
                                .addGroup(jpnAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxtDescripcion)
                                    .addComponent(jtxtProduct, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jpnAddProductLayout.createSequentialGroup()
                                        .addComponent(jtxtId_Product, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jchkActivo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jbtnBuscaArt, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jpnAddProductLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jtxtPrecioVenta, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(jtxtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnAddProductLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnAddProductLayout.createSequentialGroup()
                .addGap(135, 707, Short.MAX_VALUE)
                .addGroup(jpnAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnRCompra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblCantidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jpnAddProductLayout.setVerticalGroup(
            jpnAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnAddProductLayout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jpnAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtxtId_Product, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jchkActivo)
                    .addComponent(jbtnBuscaArt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jpnAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jpnAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jtxtPrecioCompra)
                    .addComponent(jtxtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jtxtPrecioVenta)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnCancelar)
                    .addComponent(jbtnAgregar))
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jlblCantidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnRCompra)
                .addGap(135, 135, 135))
        );

        jtbpCompra.addTab("Realizar Nueva Compra", jpnAddProduct);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtbpCompra)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jtbpCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnRCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRCompraActionPerformed
        try {
            if ("".equals(this.jtxtClaveProveedor.getText())) {
                val.msjWarn("Ingrese una referencia de proveedor para realizar la compra");
                jtbpCompra.setSelectedIndex(0);
                this.jtxtClaveProveedor.requestFocus();
            }else{
                if(jtblProduct.getRowCount() > 0){
                    System.out.println("Insertando datos");                    
                    BigInteger cve_prov = new BigInteger(jtxtClaveProveedor.getText());
                                        
                    /*
                    Compra com = new Compra(
                           cve_prov,
                           val.fechaActual(),
                           Integer.parseInt(jlblCantidad.getText()),
                            );
                    
                    long folio_c = compraDAO.saveCompra(com);
                    System.out.println("Folio: " + folio_c);
                    
                    
                    for(int i = 0; i < this.jtblProduct.getRowCount(); i ++){
                        
                        CompraDetalle cd = new CompraDetalle();
                        cd.setCompra(com);
                        cd.setId_product(jtblProduct.getValueAt(i, 0).toString());
                        cd.setCantidad(Integer.parseInt(jtblProduct.getValueAt(i, 4).toString()));
                        
                        compraDAO.saveCompraDetalle(cd);
                    }
                    * 
                    */
                    System.out.println("Registro guardado...");
                }else{
                    val.msjWarn("Agregue al menos un articulo. Lista vacia");
                }
            }
        } catch (Exception ex) {
            System.out.println("Error al guardar: " + ex.getMessage());
        }
    }//GEN-LAST:event_jbtnRCompraActionPerformed

    private void jbtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelarActionPerformed
        
    }//GEN-LAST:event_jbtnCancelarActionPerformed

    private void jtxtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtCantidadKeyTyped
        val.longitudCaga(jtxtCantidad, 4, evt);
        val.soloNumeros(evt);
    }//GEN-LAST:event_jtxtCantidadKeyTyped

    private void jtxtPrecioVentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtPrecioVentaKeyTyped
        val.longitudCaga(this.jtxtPrecioVenta, 10, evt);
    }//GEN-LAST:event_jtxtPrecioVentaKeyTyped

    private void jtxtPrecioCompraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtPrecioCompraKeyTyped
        val.longitudCaga(this.jtxtPrecioCompra, 10, evt);
    }//GEN-LAST:event_jtxtPrecioCompraKeyTyped

    private void jtxtDescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtDescripcionKeyTyped
        val.longitudCaga(this.jtxtDescripcion, 45, evt);
    }//GEN-LAST:event_jtxtDescripcionKeyTyped

    private void jtxtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDescripcionActionPerformed
        
    }//GEN-LAST:event_jtxtDescripcionActionPerformed

    private void jtxtProductKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtProductKeyTyped
        val.longitudCaga(this.jtxtProduct, 45, evt);
    }//GEN-LAST:event_jtxtProductKeyTyped

    private void jtxtId_ProductKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtId_ProductKeyTyped
        val.longitudCaga(this.jtxtId_Product, 25, evt);
        val.soloNumeros(evt);
    }//GEN-LAST:event_jtxtId_ProductKeyTyped

    private void jbtnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnComprarActionPerformed
        try {
            jtbpCompra.setSelectedIndex(1);
        } catch (Exception ex) {
            System.out.println("Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_jbtnComprarActionPerformed

    private void jbtnCancelaBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelaBusquedaActionPerformed
        try {
            val.cleanTextField(jpnProveedor);
            val.editableTextFields(jpnProveedor, true);
            jtxtClaveProveedor.requestFocus();
        } catch (Exception ex) {
            System.out.println("Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_jbtnCancelaBusquedaActionPerformed

    private void jbtnGuardaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGuardaActionPerformed
        try {
            boolean ban = true;
            mensaje = "* Verifica lo siguiente: \t";
            if (this.jtxtClaveProveedor.getText().equals("")) {
                mensaje = mensaje + "\n Ingrese la clave del proveedor";
                ban = false;
            }
            if (this.jtxtNombre.getText().equals("")) {
                mensaje = mensaje + "\n Ingrese el Nombre del proveedor";
                ban = false;
            }
            if (ban == true) {                
                Proveedor proveedor = new Proveedor(
                        new BigInteger(this.jtxtClaveProveedor.getText()),
                        this.jtxtNombre.getText(),
                        this.jtxtDireccion.getText(),
                        this.jtxtTelefono.getText());
                BigInteger cve_proveedor = proveedorDAO.saveProveedor(proveedor);
                val.msjInfo("Proveedor guardado correctamente");
                val.cleanTextField(jpnProveedor);
                System.out.println("Clave de proveedor: " + cve_proveedor);
            }else{
                val.msjInfo(mensaje);
            }
        } catch (Exception ex) {
            System.out.println("Error en operacion guardar: " + ex.getMessage());
        }
    }//GEN-LAST:event_jbtnGuardaActionPerformed

    private void jbtnBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBuscaActionPerformed
        try {
            if("".equals(this.jtxtClaveProveedor.getText())){
                val.msjWarn("Ingrese la clave del proveedor");
                this.jtxtClaveProveedor.requestFocus();
                this.jtxtClaveProveedor.setText("");
            }
            else{
                ProveedorLogic proveedorL = new ProveedorLogic();
                Proveedor prov;
                prov = proveedorL.getProveedor(new BigInteger(jtxtClaveProveedor.getText()));
                if(prov == null){
                    val.msjErr("La clave del proveedor no existe. Vuelva a intentar");
                    this.jtxtClaveProveedor.requestFocus();
                }else{
                    try{jtxtNombre.setText(prov.getNombre());}catch(Exception ex){}
                    try{jtxtDireccion.setText(prov.getDireccion());}catch(Exception ex){}
                    try{jtxtTelefono.setText(prov.getTelefono());}catch(Exception ex){}
                    try{this.jtxtClaveProveedor.setEditable(false);}catch(Exception ex){}
                }                                
            }                                    
        } catch (Exception ex) {
            System.out.println("Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_jbtnBuscaActionPerformed

    private void jbtnBuscaArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBuscaArtActionPerformed
        try{
            if("".equals(this.jtxtId_Product.getText())){
                val.msjWarn("Ingrese el codigo del producto");
                this.jtxtId_Product.requestFocus();
            }else{
                ProductLogic pl = new ProductLogic();
                Product pro = pl.getProduct(this.jtxtId_Product.getText());
                if(null == pro){
                    val.msjErr("No se ha encontrado ningun registro");
                    jtxtId_Product.requestFocus();
                }else{
                    this.jtxtProduct.setText(pro.getProduct());
                    this.jtxtDescripcion.setText(pro.getDescripcion());
                    this.jtxtPrecioCompra.setText(Double.toString(pro.getP_compra()));
                    this.jtxtPrecioVenta.setText(Double.toString(pro.getP_venta()));
                    //this.jtxtCantidad.setText(Integer.toString(pro.getCantidad()));                    
                    vActivo = pro.getActivo();
                    if(vActivo == 0){this.jchkActivo.setSelected(false);
                    }else{this.jchkActivo.setSelected(false);}
                    this.jtxtCantidad.requestFocus();                    
                }
            }                                    
        }catch(Exception ex){
            System.out.println("Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_jbtnBuscaArtActionPerformed

    private void jbtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAgregarActionPerformed
        try{
            modelo.addRow(new Object[]{this.jtxtId_Product.getText(), 
                this.jtxtProduct.getText() + " " + this.jtxtDescripcion.getText(),
                this.jtxtPrecioCompra.getText(),
                this.jtxtPrecioVenta.getText(),
                this.jtxtCantidad.getText()});
            int cantidad = 0;
            for(int i = 0; i < jtblProduct.getRowCount(); i ++){
                cantidad = cantidad + Integer.parseInt(this.jtblProduct.getValueAt(i, 4).toString());
            }
            this.jlblCantidad.setText("" + cantidad);
            val.cleanTextField(jpnAddProduct);
            this.jtxtId_Product.requestFocus();
        }catch(Exception ex){
            System.out.println("Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_jbtnAgregarActionPerformed

    private void jtxtId_ProductKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtId_ProductKeyPressed
        if(evt.getKeyChar() == KeyEvent.VK_ENTER){
            this.jbtnBuscaArt.doClick();
        }
    }//GEN-LAST:event_jtxtId_ProductKeyPressed

    private void jtxtCantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtCantidadKeyPressed
        if(evt.getKeyChar() == KeyEvent.VK_ENTER){
            this.jbtnAgregar.doClick();
        }
    }//GEN-LAST:event_jtxtCantidadKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnAgregar;
    private javax.swing.JButton jbtnBusca;
    private javax.swing.JButton jbtnBuscaArt;
    private javax.swing.JButton jbtnCancelaBusqueda;
    private javax.swing.JButton jbtnCancelar;
    private javax.swing.JButton jbtnComprar;
    private javax.swing.JButton jbtnGuarda;
    private javax.swing.JButton jbtnRCompra;
    private javax.swing.JCheckBox jchkActivo;
    private javax.swing.JLabel jlblCantidad;
    private javax.swing.JPanel jpnAddProduct;
    private javax.swing.JPanel jpnProveedor;
    private javax.swing.JTable jtblProduct;
    private javax.swing.JTabbedPane jtbpCompra;
    private javax.swing.JTextField jtxtCantidad;
    private javax.swing.JTextField jtxtClaveProveedor;
    private javax.swing.JTextField jtxtDescripcion;
    private javax.swing.JTextField jtxtDireccion;
    private javax.swing.JTextField jtxtId_Product;
    private javax.swing.JTextField jtxtNombre;
    private javax.swing.JTextField jtxtPrecioCompra;
    private javax.swing.JTextField jtxtPrecioVenta;
    private javax.swing.JTextField jtxtProduct;
    private javax.swing.JTextField jtxtTelefono;
    // End of variables declaration//GEN-END:variables

    
    private boolean getTitleTable(){
        modelo = new DefaultTableModel(){
            @Override
                public boolean isCellEditable (int row, int column){
                return false;
            }
        };
        modelo.addColumn("Codigo");
        modelo.addColumn("Prodcuto / Descripcion");        
        modelo.addColumn("P / Compra");
        modelo.addColumn("P / Venta");
        modelo.addColumn("Cantidad");
        jtblProduct.setModel(modelo);
        return true;
    }
}
