/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.puntodeventa.mvc.Views;

import com.puntodeventa.global.Entity.Usuario;
import com.puntodeventa.global.Util.TagHelper;
import com.puntodeventa.global.Util.Util;
import com.puntodeventa.global.Util.ValidacionForms;
import com.puntodeventa.global.report.viewer.printProduct;
import com.puntodeventa.mvc.Controller.AccesoFormsLogic;
import com.puntodeventa.services.DAO.UsuarioDAO;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Nato Hdez
 */
public class PuntoVentaMDI extends javax.swing.JFrame {

    public String vgetTextMenu = "";
    public Usuario user;
    public UsuarioDAO usuarioDAO;
    ValidacionForms valForm = new ValidacionForms();
    printProduct printP = new printProduct();
    AccesoFormsLogic accesoFormsLogic = new AccesoFormsLogic();
    private String NameClass = this.getClass().getSimpleName();

    public PuntoVentaMDI(int id_usuario) {
        initComponents();
        setTitle("Administración de Punto de Venta v2. - " + getUser().getNombre());
        setExtendedState(MAXIMIZED_BOTH);   
        getInitAcceso(id_usuario);
        jmnuUsuarios.setVisible(false);
        jmnuVentaByCategory.setVisible(false);
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("images/ico.png"));
        return retValue;
    }

    private void getInitAcceso(int id_usuario){
        String msj = accesoFormsLogic.getAcceso(id_usuario, NameClass);
        if(msj != null){
            valForm.msjInfo(msj);
            System.exit(0);
        }
    } 

    private Usuario getUser() {
        Usuario usuario;
        usuario = Util.getCurrentUser();
        return usuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmnuListArticulos = new javax.swing.JMenuItem();
        jmnuFormatInvent = new javax.swing.JMenuItem();
        jmnuHistVenta = new javax.swing.JMenuItem();
        jmnuHistVentaByArt = new javax.swing.JMenuItem();
        jmnuHistCompra = new javax.swing.JMenuItem();
        jmnuVentaByCategory = new javax.swing.JMenuItem();
        jmnuAdmin = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jmnuAccesos = new javax.swing.JMenuItem();
        jmnuUsuarios = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setIconImage(getIconImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formClosing(evt);
            }
        });

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/catalogos.gif"))); // NOI18N
        jMenu3.setText("Archivo");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem3.setText("Salir");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        menuBar.add(jMenu3);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Compras (1).png"))); // NOI18N
        jMenu1.setText("Catalogos");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem1.setText("Producto");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem2.setText("Compra");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        menuBar.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icono-reporte1.jpg"))); // NOI18N
        jMenu2.setText("Reportes");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jmnuListArticulos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        jmnuListArticulos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jmnuListArticulos.setText("Listado General de Articulos");
        jmnuListArticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnuListArticulosActionPerformed(evt);
            }
        });
        jMenu2.add(jmnuListArticulos);

        jmnuFormatInvent.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_MASK));
        jmnuFormatInvent.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jmnuFormatInvent.setText("Articulos para inventario");
        jmnuFormatInvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnuFormatInventActionPerformed(evt);
            }
        });
        jMenu2.add(jmnuFormatInvent);

        jmnuHistVenta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.ALT_MASK));
        jmnuHistVenta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jmnuHistVenta.setText("Historial de Venta");
        jmnuHistVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnuHistVentaActionPerformed(evt);
            }
        });
        jMenu2.add(jmnuHistVenta);

        jmnuHistVentaByArt.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK));
        jmnuHistVentaByArt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jmnuHistVentaByArt.setText("Historial de Venta por Articulo");
        jmnuHistVentaByArt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnuHistVentaByArtActionPerformed(evt);
            }
        });
        jMenu2.add(jmnuHistVentaByArt);

        jmnuHistCompra.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        jmnuHistCompra.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jmnuHistCompra.setText("Historial de Compra");
        jmnuHistCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnuHistCompraActionPerformed(evt);
            }
        });
        jMenu2.add(jmnuHistCompra);

        jmnuVentaByCategory.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jmnuVentaByCategory.setText("Venta por Categoria");
        jmnuVentaByCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnuVentaByCategoryActionPerformed(evt);
            }
        });
        jMenu2.add(jmnuVentaByCategory);

        menuBar.add(jMenu2);

        jmnuAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Acceso.png"))); // NOI18N
        jmnuAdmin.setText("Administracion");
        jmnuAdmin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem4.setText("Cambiar Contraseña");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jmnuAdmin.add(jMenuItem4);

        jmnuAccesos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jmnuAccesos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jmnuAccesos.setText("Accesos");
        jmnuAccesos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnuAccesosActionPerformed(evt);
            }
        });
        jmnuAdmin.add(jmnuAccesos);

        jmnuUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jmnuUsuarios.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jmnuUsuarios.setText("Usuarios");
        jmnuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnuUsuariosActionPerformed(evt);
            }
        });
        jmnuAdmin.add(jmnuUsuarios);

        menuBar.add(jmnuAdmin);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        frmProduct p = new frmProduct();
        desktopPane.add(p);
        p.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jmnuHistVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnuHistVentaActionPerformed
        vgetTextMenu = jmnuHistVenta.getText();
        jfrmReport frmRe = new jfrmReport();
        frmRe.setNameMenu(vgetTextMenu);
        desktopPane.add(frmRe);
        frmRe.show();
    }//GEN-LAST:event_jmnuHistVentaActionPerformed

    private void jmnuListArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnuListArticulosActionPerformed
        try {
            if (true == printP.getPrintProductList()) {
                System.out.println("Informe en pantalla...");
            }
        } catch (Exception ex) {
            System.out.println("Error while printing report listGeneral: " + ex.getMessage());
        }
    }//GEN-LAST:event_jmnuListArticulosActionPerformed

    private void jmnuHistCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnuHistCompraActionPerformed
        vgetTextMenu = jmnuHistCompra.getText();
        jfrmReport frmRe = new jfrmReport();
        frmRe.setNameMenu(vgetTextMenu);
        desktopPane.add(frmRe);
        frmRe.show();
    }//GEN-LAST:event_jmnuHistCompraActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        jfrmCompra compra = new jfrmCompra();
        desktopPane.add(compra);
        compra.show();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        frmUser usr = new frmUser();
        desktopPane.add(usr);
        usr.show();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        try {
            int op;
            op = JOptionPane.showConfirmDialog(rootPane, "Desea salir del Sistema?", "Salir del sistema", JOptionPane.OK_CANCEL_OPTION, 3);
            if (op == 0) {
                System.exit(0);
            }
        } catch (Exception ex) {
            System.out.println("Imposible salir del sistema...:" + ex.getMessage());
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void formClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formClosing
        try {
            int op;
            op = JOptionPane.showConfirmDialog(rootPane, "Desea salir del Sistema?", "Salir del sistema", JOptionPane.OK_CANCEL_OPTION, 3);
            if (op == 0) {
                System.exit(0);
            }
        } catch (Exception ex) {
            System.out.println("Imposible salir del sistema...:" + ex.getMessage());
        }
    }//GEN-LAST:event_formClosing

    private void jmnuFormatInventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnuFormatInventActionPerformed
        try {
            printP.getPrintProdToInventoryList();
        } catch (Exception ex) {
            System.out.println("Error while printing ListPorductToInventario: " + ex.getMessage());
        }
    }//GEN-LAST:event_jmnuFormatInventActionPerformed

    private void jmnuHistVentaByArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnuHistVentaByArtActionPerformed
        vgetTextMenu = jmnuHistVentaByArt.getText();
        jfrmReport frmRe = new jfrmReport();
        frmRe.setNameMenu(vgetTextMenu);
        desktopPane.add(frmRe);
        frmRe.show();
    }//GEN-LAST:event_jmnuHistVentaByArtActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jmnuAccesosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnuAccesosActionPerformed
        frmForms frmForm = new frmForms(this, true);        
        String msj = accesoFormsLogic.getAcceso(getUser().getId_usuario(), frmForm.getClass().getSimpleName());
        if (msj != null) {
            valForm.msjInfo(msj);
        } else {                                   
            frmForm.setVisible(true);
        }
    }//GEN-LAST:event_jmnuAccesosActionPerformed

    private void jmnuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnuUsuariosActionPerformed
        frmUsuarios frmUsuario = new frmUsuarios(this, true);
        frmUsuario.setVisible(true);
    }//GEN-LAST:event_jmnuUsuariosActionPerformed

    private void jmnuVentaByCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnuVentaByCategoryActionPerformed
        frmVentaByCategory ventaByCategory = new frmVentaByCategory(this, true);
        ventaByCategory.setVisible(true);
    }//GEN-LAST:event_jmnuVentaByCategoryActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jmnuAccesos;
    private javax.swing.JMenu jmnuAdmin;
    private javax.swing.JMenuItem jmnuFormatInvent;
    private javax.swing.JMenuItem jmnuHistCompra;
    private javax.swing.JMenuItem jmnuHistVenta;
    private javax.swing.JMenuItem jmnuHistVentaByArt;
    private javax.swing.JMenuItem jmnuListArticulos;
    private javax.swing.JMenuItem jmnuUsuarios;
    private javax.swing.JMenuItem jmnuVentaByCategory;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables
}
